# theme = "base24"
theme = "dark_plus_plus"

[editor]
line-number = "relative"
shell = ["bash", "-c"]
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "hidden"
  
[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding"]

[editor.lsp]
enable = true

[keys.normal]
q = ":buffer-close"
Q = ":buffer-close!"
z = ":write"
Z = ":write!"
v = "select_mode"
"@" = "record_macro"
"!" = "replay_macro"
"[" = ":buffer-previous"
"]" = ":buffer-next"

n = [ "collapse_selection", "insert_mode" ]
N = [ "add_newline_above", "move_visual_line_up" ]
space.n = "open_above"
h = [ "move_char_right", "insert_mode" ]
H = [ "add_newline_below", "move_visual_line_down" ]
space.h = "open_below"

# movement
y = "move_visual_line_up"
e = "move_char_left"
i = "move_visual_line_down"
o = "move_char_right"
Y = [ "goto_window_top", "move_visual_line_up", "align_view_center" ]
E = "goto_first_nonwhitespace"
I = [ "goto_window_bottom", "move_visual_line_down", "align_view_center" ]
O = "goto_line_end"
w = "move_next_word_end"
W = "move_next_long_word_end"
b = "move_prev_word_start"
B = "move_prev_long_word_start"
V = "match_brackets"

# text-manipulation
c = "yank" # copy
C = "yank_to_clipboard" # copy to clipboard
p = "paste_before" # paste
P = "paste_clipboard_before" # paste from clipboard
d = "delete_selection_noyank" # delete selection
x = "delete_selection" # cut
X = [ "yank_to_clipboard", "delete_selection_noyank" ] # cut to clipboard
r = "replace" # replace character
R = "replace_with_yanked" # replace
A = "replace_selections_with_clipboard" # replace with clipboard
a = [ "delete_selection_noyank", "insert_mode" ] # delete selection & insert
"backspace" = [ "move_char_left", "delete_selection_noyank" ]
u = "undo"
U = "redo"
"tab" =	"indent"
"S-tab"	= "unindent"

"+" = "surround_add"
"=" = "surround_replace"
"*" = "surround_delete"
">" = "switch_to_uppercase"
"~" = "switch_case"
"<" = "switch_to_lowercase"

# find & selection
s = "search"
S = [ "search_selection", "search" ]
g = "search_next" # goto_next_match
G = "search_prev" # goto_prev_match
F = "find_prev_char" # find_char_backward
f = "find_next_char" # find_char_forward
T = "till_prev_char" # till_char_backward
t = "find_till_char" # till_char_forward

m = "select_textobject_inner" # match inner
M = "select_textobject_around" # match outer
k = "copy_selection_on_next_line" # add cursor and selection below
K = "copy_selection_on_prev_line" # add cursor and selection above
j = "join_selections_space"
J = [ "move_visual_line_up", "join_selections_space" ]
l = "extend_line_below"
L = [ "extend_line_up", "extend_to_line_bounds" ]
"%" = "select_all"
"/" = "select_regex"
"," = "collapse_selection"
";" = "split_selection_on_newline"
# "." = repeat_last_insert
# ":" = command_mode
"'" = "flip_selections"
"\"" = "keep_primary_selection"
"minus" = "remove_primary_selection"
"_" = "trim_selections"
"&" = "align_selections"
"(" = "rotate_selections_backward"
")" = "rotate_selections_forward"

"{" = "goto_prev_change"
"}" = "goto_next_change"
space."{" = "goto_first_change"
space."}" = "goto_last_change"
space.q = ":quit"
space.Q = ":quit!"
space.l = ":lsp-restart"
space.o = ":reload-all"
space.O = ":config-reload"
space.t = "align_view_top"
space.m = "align_view_center"
space.b = "align_view_bottom"
space.M = "align_view_middle"
space.f = "file_picker_in_current_directory"
space.F = "goto_file"
space."/" = "global_search"
space.y = "goto_file_start"
space.i = "goto_file_end"
space."." = "goto_last_modification"
space.c = "toggle_comments"
space.C = "toggle_block_comments"
space.p = "hover" ## Show documentation for item under cursor in a popup (LSP)
space.e = "workspace_diagnostics_picker" ## Open workspace diagnostics picker (LSP)
space.E = "diagnostics_picker" ## Open document diagnostics picker (LSP)
space.d = "goto_definition" ## Go to definition (LSP)
space.D = "goto_type_definition" ## Go to type definition (LSP)
space.s = "symbol_picker" ## Open document symbol picker (LSP)
space.S = "workspace_symbol_picker" ## Open workspace symbol picker (LSP)
space.r = "rename_symbol" ## Rename symbol (LSP)
space.R = "select_references_to_symbol_under_cursor" ## Select symbol references (LSP)
space.a = "code_action" ## Apply code action (LSP)
# space.r = "goto_reference" ## Go to references (LSP)
# space.R = "goto_implementation" ## Go to implementation (LSP)
# space."=" = "format_selection" ## Format selection (currently nonfunctional/disabled) (LSP)
# space.g	## Debug (experimental)
# space.w	## Enter window mode

space.j = "no_op"
space."?" = "no_op"
space."'" = "no_op"
space.k = "no_op"
space.Y = "no_op"
space.P = "no_op"
space.A-c = "no_op"
"C-i" = "no_op"
"C-o" = "no_op"
"C-s" = "no_op"
"C-b" = "no_op"
"C-f" = "no_op"
"C-d" = "no_op"
"C-u" = "no_op"
"C-w" = "no_op"
# window mode
# insert mode
# picker
# prompt

[keys.select]
q = ":buffer-close"
Q = ":buffer-close!"
z = ":write"
Z = ":write!"
v = "normal_mode"
"@" = "record_macro"
"!" = "replay_macro"
"[" = ":buffer-previous"
"]" = ":buffer-next"

n = [ "collapse_selection", "insert_mode" ]
N = [ "add_newline_above", "move_visual_line_up" ]
space.n = "open_above"
h = [ "move_char_right", "insert_mode" ]
H = [ "add_newline_below", "move_visual_line_down" ]
space.h = "open_below"

# movement
y = "extend_visual_line_up"
e = "extend_char_left"
i = "extend_visual_line_down"
o = "extend_char_right"
Y = [ "goto_window_top", "extend_visual_line_up", "align_view_center" ]
E = "goto_first_nonwhitespace"
I = [ "goto_window_bottom", "extend_visual_line_down", "align_view_center" ]
O = "goto_line_end"
w = "extend_next_word_end"
W = "extend_next_long_word_end"
b = "extend_prev_word_start"
B = "extend_prev_long_word_start"
V = "match_brackets"

# text-manipulation
c = "yank" # copy
C = "yank_to_clipboard" # copy to clipboard
p = "paste_before" # paste
P = "paste_clipboard_before" # paste from clipboard
d = "delete_selection_noyank" # delete selection
x = "delete_selection" # cut
X = [ "yank_to_clipboard", "delete_selection_noyank" ] # cut to clipboard
r = "replace" # replace character
R = "replace_with_yanked" # replace
A = "replace_selections_with_clipboard" # replace with clipboard
a = [ "delete_selection_noyank", "insert_mode" ] # delete selection & insert
"backspace" = [ "move_char_left", "delete_selection_noyank" ]
u = "undo"
U = "redo"
"tab" =	"indent"
"S-tab"	= "unindent"

"+" = "surround_add"
"=" = "surround_replace"
"*" = "surround_delete"
">" = "switch_to_uppercase"
"~" = "switch_case"
"<" = "switch_to_lowercase"

# find & selection
s = "search"
S = [ "search_selection", "search" ]
g = "search_next" # goto_next_match
G = "search_prev" # goto_prev_match
F = "extend_prev_char" # find_char_backward
f = "extend_next_char" # find_char_forward
T = "extend_till_prev_char" # till_char_backward
t = "extend_till_char" # till_char_forward

m = "select_textobject_inner" # match inner
M = "select_textobject_around" # match outer
k = "copy_selection_on_next_line" # add cursor and selection below
K = "copy_selection_on_prev_line" # add cursor and selection above
j = "join_selections_space"
J = [ "move_visual_line_up", "join_selections_space" ]
l = "extend_line_below"
L = [ "extend_line_up", "extend_to_line_bounds" ]
"%" = "select_all"
"/" = "select_regex"
"," = "collapse_selection"
";" = "split_selection_on_newline"
# "." = repeat_last_insert
# ":" = command_mode
"'" = "flip_selections"
"\"" = "keep_primary_selection"
"minus" = "remove_primary_selection"
"_" = "trim_selections"
"&" = "align_selections"
"(" = "rotate_selections_backward"
")" = "rotate_selections_forward"

"{" = "goto_prev_change"
"}" = "goto_next_change"
space."{" = "goto_first_change"
space."}" = "goto_last_change"
space.q = ":quit"
space.Q = ":quit!"
space.l = ":lsp-restart"
space.o = ":reload-all"
space.O = ":config-reload"
space.t = "align_view_top"
space.m = "align_view_center"
space.b = "align_view_bottom"
space.M = "align_view_middle"
space.f = "file_picker_in_current_directory"
space.F = "goto_file"
space."/" = "global_search"
space.y = "goto_file_start"
space.i = "goto_file_end"
space."." = "goto_last_modification"
space.c = "toggle_comments"
space.C = "toggle_block_comments"
space.p = "hover" ## Show documentation for item under cursor in a popup (LSP)
space.e = "workspace_diagnostics_picker" ## Open workspace diagnostics picker (LSP)
space.E = "diagnostics_picker" ## Open document diagnostics picker (LSP)
space.d = "goto_definition" ## Go to definition (LSP)
space.D = "goto_type_definition" ## Go to type definition (LSP)
space.s = "symbol_picker" ## Open document symbol picker (LSP)
space.S = "workspace_symbol_picker" ## Open workspace symbol picker (LSP)
space.r = "rename_symbol" ## Rename symbol (LSP)
space.R = "select_references_to_symbol_under_cursor" ## Select symbol references (LSP)
space.a = "code_action" ## Apply code action (LSP)
# space.r = "goto_reference" ## Go to references (LSP)
# space.R = "goto_implementation" ## Go to implementation (LSP)
# space."=" = "format_selection" ## Format selection (currently nonfunctional/disabled) (LSP)
# space.g	## Debug (experimental)
# space.w	## Enter window mode

space.j = "no_op"
space."?" = "no_op"
space."'" = "no_op"
space.k = "no_op"
space.Y = "no_op"
space.P = "no_op"
space.A-c = "no_op"
"C-i" = "no_op"
"C-o" = "no_op"
"C-s" = "no_op"
"C-b" = "no_op"
"C-f" = "no_op"
"C-d" = "no_op"
"C-u" = "no_op"
"C-w" = "no_op"
