[language-server.rust-analyzer]
command = "rust-analyzer"
config.check.command = "clippy"
config.cachePriming.enable = false
config.inlayHints.bindingModeHints.enable = false
config.inlayHints.closingBraceHints.minLines = 10
config.inlayHints.closureReturnTypeHints.enable = "with_block"
config.inlayHints.discriminantHints.enable = "fieldless"
config.inlayHints.lifetimeElisionHints.enable = "skip_trivial"
config.inlayHints.typeHints.hideClosureInitialization = false

[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rs|rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
shebangs = ["rust-script", "cargo"]
auto-format = true
comment-tokens = ["//", "///", "//!"]
block-comment-tokens = [
  { start = "/*", end = "*/" },
  { start = "/**", end = "*/" },
  { start = "/*!", end = "*/" },
]
language-servers = [ "rust-analyzer" ]
indent = { tab-width = 4, unit = "    " }
persistent-diagnostic-sources = ["rustc", "clippy"]

[language-server.nu-lsp]
command = "nu"
args = ["--lsp"]

[[language]]
name = "nu"
language-servers = ["nu-lsp"]
