# UI
"ui.background"                   = { bg = "base00" }
# "ui.background.seperator"         =
"ui.cursor"                       = { fg = "base04", modifiers = ["reversed"] }
# "ui.cursor.normal"                =
# "ui.cursor.insert"                =
# "ui.cursor.select"                =
"ui.cursor.match"                 = { fg = "light_yellow", modifiers = ["underlined"] }
"ui.cursor.primary"               = { fg = "base05", modifiers = ["reversed"] }
# "ui.cursor.primary.normal"        =
# "ui.cursor.primary.insert"        =
# "ui.cursor.primary.select"        =
# "ui.debug.breakpoint"             =
# "ui.debug.active"                 =
"ui.gutter"                       = { bg = "base00" }
# "ui.gutter.selected"              =
"ui.linenr"                       = { fg = "base03", bg = "base00" }
"ui.linenr.selected"              = { fg = "base05", bg = "base00", modifiers = ["bold"] }
"ui.statusline"                   = { fg = "base04", bg = "base01" }
# "ui.statusline.inactive"          = 
# "ui.statusline.normal"            = 
# "ui.statusline.insert"            = 
# "ui.statusline.select"            =
# "ui.statusline.seperator"         =
"ui.bufferline"                   = { fg = "base04", bg = "base00" }
"ui.bufferline.active"            = { fg = "base06", bg = "base01" }
# "ui.bufferline.background"        =
"ui.popup"                        = { bg = "base01" }
# "ui.popup.info"                   =
# "ui.picker.header"                =
# "ui.picker.header.column"         =
# "ui.picker.header.column.active"  =
"ui.window"                       = { bg = "base01" }
"ui.help"                         = { fg = "base06", bg = "base01" }
"ui.text"                         = "base05"
"ui.text.focus"                   = "base05"
# "ui.text.inactive"                =
# "ui.text.info"                    =
# "ui.text.directory"               =
"ui.virtual.whitespace"           = "base03"
# "ui.virtual.indent-guide"         = 
# "ui.virtual.inlay-hint"           = 
# "ui.virtual.inlay-hint.parameter" = 
# "ui.virtual.inlay-hint.type"      = 
# "ui.virtual.wrap"                 = 
# "ui.virtual.jump-label"           = 
"ui.menu"                         = { fg = "base05", bg = "base01" }
"ui.menu.selected"                = { fg = "base01", bg = "base04" }
# "ui.menu.scroll"                  = 
"ui.selection"                    = { bg = "base02" }
# "ui.selection.primary"            = 
# "ui.highlight"                    = 
# "ui.highlight.frameline"          = 
# "ui.cursorline.primary"           = 
# "ui.cursorline.secondary"         = 
# "ui.cursorcolumn.primary"         = 
# "ui.cursorcolumn.secondary"       = 
"warning"                         = "dark_orange"
"error"                           = "dark_red"
"info"                            = "light_blue"
"hint"                            = "base03"
"diagnostic"                      = { modifiers = ["underlined"] }
# "diagnostic.hint"                 = 
# "diagnostic.info"                 = 
# "diagnostic.warning"              = 
# "diagnostic.error"                = 
# "diagnostic.necessary"            = 
# "diagnostic.deprecated"           = 
# "tabstop"                         =

# MARKUP
"markup.heading"                  = "light_blue"
"markup.list"                     = "dark_red"
"markup.bold"                     = { fg = "light_yellow", modifiers = ["bold"] }
"markup.italic"                   = { fg = "light_magenta", modifiers = ["italic"] }
"markup.strikethrough"            = { modifiers = ["crossed_out"] }
"markup.link.url"                 = { fg = "dark_orange", modifiers = ["underlined"] }
"markup.link.text"                = "dark_red"
"markup.quote"                    = "light_cyan"
"markup.raw"                      = "dark_green"

# SYNTAX
"operator"                        = "base05"
"comment"                         = "base03"
"comment.block.documentation"     = "grayish_blue"
"string"                          = "dark_green"
"constant"                        = "dark_orange"
"constant.builtin"                = "dark_orange"
"constant.numeric"                = "dark_orange"
"constant.character.escape"       = "dark_red"
"keyword"                         = "light_magenta"
"type.builtin"                    = "light_magenta"
"type"                            = "light_yellow"
"type.enum.variant"               = "dark_green"
"variable.other.member"           = "dark_green"
"variable"                        = "dark_red"
"variable.builtin"                = "deep_red"
"function"                        = "light_blue"
"constructor"                     = "light_blue"
"function.macro"                  = "deep_blue"
"keyword.directive"               = "deep_blue"
"namespace"                       = "deep_blue"
"tag"                             = "dark_red"
"attribute"                       = "dark_orange"
"special"                         = "light_blue"
"label"                           = "light_magenta"
"diff.plus"                       = "dark_green"
"diff.delta"                      = "dark_orange"
"diff.minus"                      = "dark_red"

[palette]
base00 = "#080808" # Default Background
base01 = "#181818" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#333333" # Selection Background
base03 = "#585858" # Comments, Invisibles, Line Highlighting
base04 = "#b8b8b8" # Dark Foreground (Used for status bars)
base05 = "#d8d8d8" # Default Foreground, Caret, Delimiters, Operators
base06 = "#e8e8e8" # Light Foreground (Not often used)
base07 = "#f8f8f8" # Light Background (Not often used)

dark_red = "#ab4642" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted    # dark red
deep_red = "#af3c26"
dark_orange = "#dc9656" # Constants, XML Attributes, Markup Link Url, Diff Modified            # dark orange
deep_orange = "#000000"
light_yellow = "#edc677" # Classes, Markup Bold, Search Text Background                         # light yellow
deep_yellow = "#000000"
dark_green = "#a1b56c" # Strings, Type Members, Inherited Class, Markup Code, Diff Inserted   # dark green
deep_green = "#000000"
light_cyan = "#8fc7bf" # Support, Markup Quotes                                               # light cyan
deep_cyan = "#000000"
light_blue = "#75b7c7" # Functions, Methods, Attribute IDs, Headings                          # light blue
deep_blue = "#57afd7" # Macros, Preprocessor Directives                                      # deep blue
grayish_blue = "#8b9eb7" # Documentation Comment                                                # grayish-blue
light_magenta = "#ba8baf" # Keywords, Storage, Selector, Markup Italic, Diff Changed             # light magenta
dark_magenta = "#a576a0" # Namespaces                                                           # dark magenta
