# theme = "base24"
theme = "my_dark_plus"

# "amberwood", "autumn_night", "ayu_dark", "ayu_evolve", "catppuccin_frappe",
# "catppuccin_macchiato", "catppuccin_mocha", "everblush", "fleet_dark",
# "github_dark", "github_dark_colorblind", "github_dark_dimmed",
# "github_dark_high_contrast", "github_dark_tritanopia", "gruvbox",
# "gruvbox_dark_hard", "jellybeans", "kanagawa", "kaolin-valley-dark",
# "material_deep_ocean", "mellow", "monokai", "monokai_aqua", "monokai_pro",
# "monokai_pro_machine", "monokai_pro_octagon", "monokai_pro_ristretto",
# "monokai_pro_spectrum", "new_moon", "nightfox", "nord-night", "nord",
# "onedark", "papercolor-dark", "penumbra+", "pop-dark", "rasmus", "snazzy",
# "solarized_dark", "sonokai", "tokyonight", "varua", "vim_dark_high_contrast",
# "zed_onedark"

[editor]
line-number = "relative"
shell = ["zsh", "-c"]
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "hidden"
  
[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding"]

[editor.lsp]
enable = true

[keys.normal]
q = ":buffer-close"
Q = ":buffer-close!"
z = ":write"
Z = ":write!"
h = [ "collapse_selection", "insert_mode" ]
n = [ "move_char_right", "insert_mode" ]
v = "select_mode"
"#" = "record_macro"
"@" = "replay_macro"
"[" = ":buffer-previous"
"]" = ":buffer-next"

space.q = ":quit"
space.Q = ":quit!"
space.l = ":lsp-restart"
space.o = ":reload-all"
space.O = ":config-reload"
space.t = "align_view_top"
space.m = "align_view_center"
space.b = "align_view_bottom"
space.M = "align_view_middle"
space.f = "file_picker_in_current_directory"
space.F = "goto_file"
space."/" = "global_search"
space.y = "goto_file_start"
space.i = "goto_file_end"
space."." = "goto_last_modification"
space.c = "toggle_comments"
space.C = "toggle_block_comments"
space.p = "hover" ## Show documentation for item under cursor in a popup (LSP)
space.e = "workspace_diagnostics_picker" ## Open workspace diagnostics picker (LSP)
space.E = "diagnostics_picker" ## Open document diagnostics picker (LSP)
space.d = "goto_definition" ## Go to definition (LSP)
space.D = "goto_type_definition" ## Go to type definition (LSP)
space.s = "symbol_picker" ## Open document symbol picker (LSP)
space.S = "workspace_symbol_picker" ## Open workspace symbol picker (LSP)
space.r = "rename_symbol" ## Rename symbol (LSP)
space.R = "select_references_to_symbol_under_cursor" ## Select symbol references (LSP)
space.a = "code_action" ## Apply code action (LSP)
# space.r = "goto_reference" ## Go to references (LSP)
# space.R = "goto_implementation" ## Go to implementation (LSP)
# space."=" = "format_selection" ## Format selection (currently nonfunctional/disabled) (LSP)
# space.g	## Debug (experimental)
# space.w	## Enter window mode

# movement
y = "move_visual_line_up"
e = "move_char_left"
i = "move_visual_line_down"
o = "move_char_right"
Y = [ "goto_window_top", "move_visual_line_up", "align_view_center" ]
E = "goto_first_nonwhitespace"
I = [ "goto_window_bottom", "move_visual_line_down", "align_view_center" ]
O = "goto_line_end"
w = "move_next_word_end"
W = "move_next_long_word_end"
b = "move_prev_word_start"
B = "move_prev_long_word_start"
V = "match_brackets"

# text-manipulation
c = "yank" # copy
C = ":clipboard-yank" # copy to clipboard
p = "paste_before" # paste
P = "paste_clipboard_before" # paste from clipboard
d = "delete_selection_noyank" # delete selection
D = "change_selection" # delete selection & insert 
x = "delete_selection" # cut
X = [ ":clipboard-yank", "delete_selection_noyank" ] # cut to clipboard
r = "replace" # replace character
R = "replace_with_yanked" # replace
"backspace" = [ "move_char_left", "delete_selection_noyank" ]
u = "undo"
U = "redo"
k = "copy_selection_on_next_line" # add cursor and selection below
K = "copy_selection_on_prev_line" # add cursor and selection above
"tab" =	"indent"
"S-tab"	= "unindent"
a = "open_above"
A = [ "add_newline_above", "move_visual_line_up" ]
g = "open_below"
G = [ "add_newline_below", "move_visual_line_down" ]

"+" = "surround_add"
"=" = "surround_replace"
"minus" = "surround_delete"
">" = "switch_to_uppercase"
"~" = "switch_case"
"<" = "switch_to_lowercase"

# find & selection
s = "search"
S = [ "search_selection", "search" ]
M = "search_prev" # prev_match
m = "search_next" # next_match
F = "find_prev_char" # find_char_backward
f = "find_next_char" # find_char_forward
T = "till_prev_char" # till_char_backward
t = "find_till_char" # till_char_forward

N = "select_textobject_around"
H = "select_textobject_inner"
j = "join_selections_space"
J = [ "move_visual_line_up", "join_selections_space" ]
L = [ "extend_line_up", "extend_to_line_bounds" ]
l = "extend_line_below"
"%" = "select_all"
"/" = "select_regex"
"," = "collapse_selection"
";" = "split_selection_on_newline"
# "." = repeat_last_insert
# ":" = command_mode
"'" = "flip_selections"
"\"" = "keep_primary_selection"
"_" = "remove_primary_selection"
"(" = "rotate_selections_backward"
")" = "rotate_selections_forward"
"*" = "trim_selections"
"^" = "align_selections"

space.j = "no_op"
space."?" = "no_op"
space."'" = "no_op"
space.k = "no_op"
space.Y = "no_op"
space.P = "no_op"
space.h = "no_op"
space.A-c = "no_op"
"C-i" = "no_op"
"C-o" = "no_op"
"C-s" = "no_op"
"C-b" = "no_op"
"C-f" = "no_op"
"C-d" = "no_op"
"C-u" = "no_op"
"C-w" = "no_op"
# window mode
# insert mode
# picker
# prompt

[keys.select]
q = ":buffer-close"
Q = ":buffer-close!"
z = ":write"
Z = ":write!"
h = [ "collapse_selection", "insert_mode" ]
n = [ "move_char_right", "insert_mode" ]
v = "normal_mode"
"#" = "record_macro"
"@" = "replay_macro"
"[" = ":buffer-previous"
"]" = ":buffer-next"

space.q = ":quit"
space.Q = ":quit!"
space.l = ":lsp-restart"
space.o = ":reload-all"
space.O = ":config-reload"
space.t = "align_view_top"
space.m = "align_view_center"
space.b = "align_view_bottom"
space.M = "align_view_middle"
space.f = "file_picker_in_current_directory"
space.F = "goto_file"
space."/" = "global_search"
space.y = "goto_file_start"
space.i = "goto_file_end"
space."." = "goto_last_modification"
space.c = "toggle_comments"
space.C = "toggle_block_comments"
space.p = "hover" ## Show documentation for item under cursor in a popup (LSP)
space.e = "workspace_diagnostics_picker" ## Open workspace diagnostics picker (LSP)
space.E = "diagnostics_picker" ## Open document diagnostics picker (LSP)
space.d = "goto_definition" ## Go to definition (LSP)
space.D = "goto_type_definition" ## Go to type definition (LSP)
space.s = "symbol_picker" ## Open document symbol picker (LSP)
space.S = "workspace_symbol_picker" ## Open workspace symbol picker (LSP)
space.r = "rename_symbol" ## Rename symbol (LSP)
space.R = "select_references_to_symbol_under_cursor" ## Select symbol references (LSP)
space.a = "code_action" ## Apply code action (LSP)
# space.r = "goto_reference" ## Go to references (LSP)
# space.R = "goto_implementation" ## Go to implementation (LSP)
# space."=" = "format_selection" ## Format selection (currently nonfunctional/disabled) (LSP)
# space.g	## Debug (experimental)
# space.w	## Enter window mode

# movement
y = "extend_visual_line_up"
e = "extend_char_left"
i = "extend_visual_line_down"
o = "extend_char_right"
Y = [ "goto_window_top", "extend_visual_line_up", "align_view_center" ]
E = "goto_first_nonwhitespace"
I = [ "goto_window_bottom", "extend_visual_line_down", "align_view_center" ]
O = "goto_line_end"
w = "extend_next_word_end"
W = "extend_next_long_word_end"
b = "extend_prev_word_start"
B = "extend_prev_long_word_start"
V = "match_brackets"

# text-manipulation
c = "yank" # copy
C = ":clipboard-yank" # copy to clipboard
p = "paste_before" # paste
P = "paste_clipboard_before" # paste from clipboard
d = "delete_selection_noyank" # delete selection
D = "change_selection" # delete selection & insert 
x = "delete_selection" # cut
X = [ ":clipboard-yank", "delete_selection_noyank" ] # cut to clipboard
r = "replace" # replace character
R = "replace_with_yanked" # replace
"backspace" = [ "move_char_left", "delete_selection_noyank" ]
u = "undo"
U = "redo"
k = "copy_selection_on_next_line" # add cursor and selection below
K = "copy_selection_on_prev_line" # add cursor and selection above
"tab" =	"indent"
"S-tab"	= "unindent"
a = "open_above"
A = [ "add_newline_above", "move_visual_line_up" ]
g = "open_below"
G = [ "add_newline_below", "move_visual_line_down" ]

"+" = "surround_add"
"=" = "surround_replace"
"minus" = "surround_delete"
">" = "switch_to_uppercase"
"~" = "switch_case"
"<" = "switch_to_lowercase"

# find & selection
s = "search"
S = [ "search_selection", "search" ]
M = "search_prev" # prev_match
m = "search_next" # next_match
F = "extend_prev_char" # find_char_backward
f = "extend_next_char" # find_char_forward
T = "extend_till_prev_char" # till_char_backward
t = "extend_till_char" # till_char_forward

N = "select_textobject_around"
H = "select_textobject_inner"
j = "join_selections_space"
J = [ "move_visual_line_up", "join_selections_space" ]
L = [ "extend_line_up", "extend_to_line_bounds" ]
l = "extend_line_below"
"%" = "select_all"
"/" = "select_regex"
"," = "collapse_selection"
";" = "split_selection_on_newline"
# "." = repeat_last_insert
# ":" = command_mode
"'" = "flip_selections"
"\"" = "keep_primary_selection"
"_" = "remove_primary_selection"
"(" = "rotate_selections_backward"
")" = "rotate_selections_forward"
"*" = "trim_selections"
"^" = "align_selections"

space.j = "no_op"
space."?" = "no_op"
space."'" = "no_op"
space.k = "no_op"
space.Y = "no_op"
space.P = "no_op"
space.h = "no_op"
space.A-c = "no_op"
"C-i" = "no_op"
"C-o" = "no_op"
"C-s" = "no_op"
"C-b" = "no_op"
"C-f" = "no_op"
"C-d" = "no_op"
"C-u" = "no_op"
"C-w" = "no_op"

# "goto_prev_diag"
# "goto_prev_function"
# "goto_prev_parameter"
# "goto_prev_class"
# "goto_prev_comment"
# "goto_prev_test"
# "goto_prev_paragraph"
# "select_prev_sibling"
# "goto_prev_change"
# "goto_first_change"
# "goto_next_diag"
# "goto_next_function"
# "goto_next_parameter"
# "goto_next_class"
# "goto_next_comment"
# "goto_next_test"
# "goto_next_paragraph"
# "select_next_sibling"
# "goto_next_change"
# "goto_last_change"
# "buffer_picker"
# "goto_last_accessed_file"
# "goto_last_modified_file"
# "half_page_up"
# "goto_window_center"
# "half_page_down"
#  = "goto_first_diag"
#  = "goto_last_diag"
#  = "decrement"
#  = "increment"
#  = "select_register"
#  = "split_selection"
# "shrink_selection"
# "expand_selection"
# "" = "jump_backward"
# "" = "jump_forward"
# "" = "save_selection"
# "rotate_selection_contents_backward"
# "rotate_selection_contents_forward"
# C-o = [":new", ":insert-output ~/.config/lf/lf-pick", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!" ]
# "earlier"
# "later"
# "goto_line_start"
# "file_picker"
# "shell_pipe" # replace output
# "shell_insert_output" # pastes new output
# "page_up"
# "page_down"
# "last_picker"
# "command_palette"
# "join_selections"
# "move_next_word_start"
# "move_next_long_word_start"
